### ISSUE TITLE
Implement H+LP insertion

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/StringDict#10]
Para insertar un String P[1, m] calculamos nuevamente su posicion i en T y desde T[i] buscamos secuencialmente (volvemos al principio si llegamos al final de la tabla) el primer lugar vacıo T[j] donde ubicamos a P. Considerando suposiciones razonables sobre la funcion de hash utilizada y la ocupacion de la tabla esta implementacion toma tiempo O(1).

El espacio ocupado por esta implementacion es O(N + k)

**Algoritmo:**
- Calcula el hashCode de key
- Accedemos a dicha posición:
  - si está vacío lo insertamos
  - si no, intentamos con la siguiente posición (volviendo al inicio del arreglo si es necesario) hasta encontrar un espacio vacío
    - si encontramos un espacio vacío se inserta el value allí
    - si no, la tabla de hash está llena y no insertará nada

**Comment by AnnBenavides** [comment]
Mencinado algunos detalles al cerrar la issue #8 sobre la implementación de una List limitada en vez de el arreglo (para hacer match con StringDictionary)
