### ISSUE TITLE
What do if words have diferent start

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/StringDict#14]
Eso xD

**Comment by AnnBenavides** [comment]
En vola te sirve lo que detallan al final del enunciado ( #18 ), que cada palabra debe terminar con el caracter $ que tiene un valor lexicográfico menor a cualquier otro símbolo, así insertas primero ese símbolo y que el resto se ordene solito (?)

**Comment by AnnBenavides** [comment]
@AnnBenavides @BastyZ

**Comment by BastyZ** [comment]
@AnnBenavides definitivamente no puede ser binario, por lo que ha de quedarse un `ArrayList` de nodos ordenados de menor a mayor (recordar que '$' es la cosa con menor valor) donde se incluyan todas las variaciones de caracteres que aparezcan.
