### ISSUE TITLE
Similarity between Texts

### ISSUE THREAD

**Issue by AnnBenavides** [BastyZ/StringDict#16]
**Se pide medir la similitud entre dos textos** Sean T1 y T2 dichos textos, T1T2 será su concatenación y P el conjunto de palabras presentes en esta última. Definimos la similitud entre T1 y T2 como:

![image](https://user-images.githubusercontent.com/15055039/32411642-b8d6e980-c1bf-11e7-95e4-48dff8ba5ed6.png)

donde _count_ retorna el número de palabras _s_ presentes en el _texto_ , si _s_ no es especificado, retorna el número de palabras del _texto_

**Algoritmo:** 
- [x] Separamos ambos textos en palabras
- [x] Utilizamos estas palabras como conjunto de llaves _diccionario_ (String key)
- [x] Los valores asociados a las llaves corresponden a un par que repesenta la frecuencia de aparición de la palabra en cada uno de los textos, T1 y T2
- [x] Hacemos un recorrido por los valores del _diccionario_

**Comment by BastyZ** [comment]
Avanzando
