### ISSUE TITLE
About text

### ISSUE THREAD

**Issue by AnnBenavides** [BastyZ/StringDict#17]
- Utilice, al menos, textos de **lenguaje natural**
- **Preprocese** los textos que usará
-- elimine saltos de línea y puntuación
-- lleve todo a minúsculas
- Asegurece de que sus textos tengan **largos de n=2^i palabras** aproximadamente con i entre 10 y 20
- Asegurese de tener al menos dos textos diferentes de cada largo para realizar la pruebas de similitud ( #16 )

**Comment by BastyZ** [comment]
Con el archivo `process.py` se eliminó todo menos los saltos de linea, al menos yo lo encuentro piola para no asesinar al BufferedReader y no cortar las palabras en mitades por accidente
