### ISSUE TITLE
Create Structure and Constructor of TernarySearchTree

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/StringDict#5]
Los ABT consisten en nodos etiquetados con sımbolos en Σ y tres hijos. La idea es similar a la de los Trie; a medida que se avanza en el arbol (en profundidad) se van identificando los sımbolos del String en el Diccionario, sin embargo, la identificacion de un sımbolo no es tan directa como lo es en un Trie.
Un nodo en un ABT etiquetado con el sımbolo s tiene como hijo del centro a un ABT que representa
los Strings que comienzan con el sımbolo s. Por otro lado, el hijo izquierdo es un ABT que contiene
los Strings que empiezan con un sımbolo menor a s.Y de manera analoga el hijo derecho tiene un
ABT que contiene los Strings que empiezan con un sımbolo mayor a s

**Comment by AnnBenavides** [comment]
Se creo la interfaz de nodos ItstNode, para el nodo vacío NulltstNode y el nodo completo tstNode
