### ISSUE TITLE
Implement TST search

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/StringDict#6]
Al igual que en un Trie, para buscar un String P[1, m], se avanza sımbolo por sımbolo en P. Si se esta analizando P[i], al entrar en un nodo:
- Si este tiene como etiqueta P[i], se desciende por su hijo del centro buscando ahora P[i + 1].
- Si la etiqueta es menor a P[i], este se busca en el hijo derecho.
- Si es mayor, se busca en el hijo izquierdo.

Si en algun momento se llega a un arbol vacıo antes de procesar completamente P, entonces P no es parte del Diccionario. Se muestra que en promedio esto toma O(m + ln n).

**Algoritmo:**
* si la llave es valida
    * agregamos # al final de key
    * iniciamos la busqueda recursiva con el nodo raiz, el string key e index 0*/

**Comment by AnnBenavides** [comment]
se creó la función recursiva **-recursiveSearch(ItstNode node, String str, int index):List<Integer>** que hace lo siguiente:

    * si el nodo es null retornamos un arreglo vacio
    * si el caracter en el la posición index del string str es MENOR al dato guardado en node
    * - seguimos la busqueda desde el hijo izquierdo del nodo, el mismo str e index
    * si el caracter en el la posición index del string str es MAYOR al dato guardado en node
    * - seguimos la busqueda desde el hijo derecho del nodo, el mismo str e index
    * sino, es decir, el caracter evaluado en str es IGUAL al dato de node
    * - si el index está al final de str, retornamos el valor guardado en el node
    * - sino seguimos la búsqueda por el hijo de al medio, con el mismo str y aumentamos el index
