### ISSUE TITLE
Implement TST insertion

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/StringDict#7]
Un nodo en un ABT etiquetado con el sımbolo s tiene como hijo del centro a un ABT que representa
los Strings que comienzan con el sımbolo s. Por otro lado, el hijo izquierdo es un ABT que contiene
los Strings que empiezan con un sımbolo menor a s.Y de manera analoga el hijo derecho tiene un
ABT que contiene los Strings que empiezan con un sımbolo mayor a s

Para insertar en un ABT, primero se hace una busqueda de P. Sea P[i, m] el sufijo del String que falto por procesar y r la referencia al nodo vacıo donde termino la busqueda de P. Lo que se hace entonces es insertar P[i, m] en r como si fuera un Trie, es decir, creando nodos unidos por su referencia central que tienen como etiquetas los sımbolos de P[i, m].

**Implementar en las clases:**
- [x] NullTstNode
- [x] tstNode
- [x] tst

**Algoritmo para tst:**
  * si la llave es valida
  * -agregamos # al final del string
  * -inserta desde la raiz, dicho key y value con el index a partir de 0*/
pd. le deja toda la pega a los nodos :D

**Comment by AnnBenavides** [comment]
Para _NullTstNode_ se tiene el siguiente algoritmo de inserción:

    * insertar un nodo nuevo para el caracter en la posicion index del string key
    * se avanza el index, si no hay más string se agrega el value a ese nodo
    * si no avanzamos caracter por caracter insertandolos segun los criterios dados
    * se entrega el pirmer nodo creado

**Comment by AnnBenavides** [comment]
Para _tstNode_ se tiene el siguiente algoritmo recursivo:
    * si el caracter en el la posición index del string key es MENOR a data
    * - insertamos en el hijo izquierdo, con la misma key, value e index 
    *   y el resultado lo setea como hijo izquierdo
    * si el caracter en el la posición index del string key es MAYOR a data
    * - insertamos en el hijo derecho, con la misma key, value e index 
    *   y el resultado lo setea como hijo derecho
    * si el caracter en el la posición index del string key es IGUAL a data
    * - si estamos al final de key agregamos value
    * - sino, insertamos en el hijo de al medio el mismo key y value pero aumentamos index
    *   y el resultado se setea como este hijo
