### ISSUE TITLE
Create Structure and Constructor of H+LP

### ISSUE THREAD

**Issue by BastyZ** [BastyZ/StringDict#8]
Sea h : Σ∗ → Z una funcion de hash para Strings y T[0, k − 1], con n ≤ k, un arreglo de
Strings llamado tabla de hash. Otra forma de implementar un Diccionario de Strings consiste en
guardar los Strings en la tabla de hash, en las posiciones dadas segun la funcion de hash. En caso que exista una colision se prueba en la siguiente posicion de T sucesivamente. A este metodo de resolucion de colisiones se le conoce como Linear Probing.

**Comment by AnnBenavides** [comment]
Se creará un  clase elemento que guarde la clave en hash y la palabra, para utilizarlo en la tabla de hash
- [x] **+htItem( String key, int value) **
con las variables públicas key y value

**Comment by AnnBenavides** [comment]
**Sobre función de hash**
Asigna un número "único" de acceso a un dato (en este caso una palabra) con las siguientes propiedades
-  siempre retorna un número para un objeto
-  dos objetos iguales siempre tendrán el mismo número
-  dos objetos diferentes no siempre tendrán diferente número

**Hash Table**
-  Crear un arreglo de tamaño k (con k el largo del arreglo de strings en nuestro caso)
- Elegir una función de hash _h_ que mapee los objetos (strings) en números de 0 a k-1
-  Colocar estos objetos en un arreglo cuyos índices sean la función de hash : HashTable[h (object)]
* obs: Java tiene su propia función d ehash: Object.hashCode(), pero podría retornar valores negativos por lo que se propone unafunción d ehash de la siguietne forma:
- [x] **Math.abs(string.hashCode())%k**

**Colisiones: Linear Probing**
Cuando agregamos objetos a la tabla de hash, es posible que diferentes objetos (usando el método _Object.equals()_ pueda tener el mísmo número de hash. Entonces
-  si no podemos insertar el objeto en el índice _i_ (por que ya tiene un elemento)
-  intentamos insertarlo en el siguiente espacio _i+1_
-  si este también está ocupado, lo intentamos en _i+2_ y así
- si llega al final del arreglo comienza a buscar espacios vacíos desde el principio
- si no hay espacios vacios es por que la tabla esta llena y no puede almacenar más elementos, entonces falla

(fuente: https://www.cs.cmu.edu/~adamchik/15-121/lectures/Hashing/hashing.html
http://www.cs.rmit.edu.au/online/blackboard/chapter/05/documents/contribute/chapter/05/linear-probing.html)

**Comment by AnnBenavides** [comment]
Se usó un areglo de hashItem para almacenar los elementos:
TODO ver una implementación de List que logre limitar la cantidad de elementos, sino habrá que harcodear por que no me gusta esta implementación con el arreglo xD
